name: Run Jest Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Install dependencies
      - name: Install dependencies
        run: npm install --force

      # Run Jest tests
      - name: Run Jest tests
        run: npm run test

      # Optional: Upload test results to GitHub (for better insights)
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: results
          path: ./test-results
